### ISSUE TITLE
How to scale Langevin Noise ? 

### ISSUE THREAD

**Issue by rb876** [gmarceaucaron/natural-langevin-dynamics-for-neural-networks#1]
Hi I am wondering if you scale the Langevin noise with respect to the sqrt of the points in the data-set, for MNIST 50 thousands points, is that right ?

**Comment by gmarceaucaron** [comment]
Yes, you can see it in Algorithm 1 of the associated [paper](https://arxiv.org/pdf/1712.01076.pdf) and it is implemented in `metriclinear.lua`.
